### PR TITLE
BUG: fix custom functions starting with keywords

### LINKED ISSUE #51: Custom Functions starting with keywords
Custom Functions starting with keywords tokenizes the keyword within the name of the function instead of recognizing the whole function.

**To Reproduce**
1. write a function that starts with a keyword
2. see errors

for example `integer` contains the keyword `in` see screenshot

**Screenshots**
Screen Shot 2020-04-06 at 4 13 42 PM

**Notes**
* stardog sparql parser specific

### PR DESCRIPTION
**Pull request by cchaffatt**
## bug [51](#51)
keyword at the beginning of a custom function being identified ie `integer` is read as `in` + `teger`

* **changes**
  * uncomment `test` with issue
  * fix #51 
  * use `longer_alt` solution
  * refactor

* **solutions**
  *  `/\b${TOKEN}\b/` => nest token in boundary matcher in regex
  *  [chevrotain/issues/566](https://github.com/SAP/chevrotain/issues/566) => add `Unknown` token as `longer_alt` option for keywords. see [sample](https://github.com/SAP/chevrotain/blob/master/examples/lexer/keywords_vs_identifiers/keywords_vs_identifiers.js).

* **screenshots**
unknown

### CODE REVIEW

**Comment by anneeb** [comment]
I think I prefer the `longer_alt` solution. It's similar to what we're doing in the `GraphQL` pareser with `Names` already. I like the idea of a `createKeywordToken` helper function, although we may want to allow the `longer_alt` to be overridden or re-order the tokens for cases such as `MAX_LENGTH` and `MAX`.

We can definitely simplify SPARQL's `UNKNOWN` token as the `A` keyword as part of this too. It looks like the definition and ordering `A` after `UNKNOWN` was a solution for this same problem.

**Comment by cchaffatt** [comment]
Yes, I like it's better as well but I couldn't figure out why some tests were failing. I think this `A` keyword extraction will do the trick. I'll try it out and add the ability to override `long_alt` in the utility method.

File: src/helpers/chevrotain.ts [hunk 1]
```diff
@@ -0,0 +1,12 @@
+import { createToken, ITokenConfig } from 'chevrotain';
```
Comment (anneeb) [inline src/helpers/chevrotain.ts:1]: I don't believe this file is being used

File: src/sms/tokens.ts [hunk 2]
```diff
@@ -1,5 +1,6 @@
 const { sparqlTokenMap, stardogSparqlTokens } = require('../sparql/tokens');
-import { TokenType, createToken, IToken } from 'chevrotain';
+import { TokenType, IToken } from 'chevrotain';
+import { createKeyword } from '../sparql/keywords';
```
Comment (anneeb) [inline src/sms/tokens.ts:3]: not sure if it matters here, but this might also be a place where we need to use CommonJS syntax: https://github.com/SAP/chevrotain/issues/345

File: src/sms/tokens.ts [hunk 3]
```diff
@@ -80,7 +63,7 @@ export const smsTokenMap = {
     },
     line_breaks: true,
   }),
-  JsonBlock: createToken({
+  JsonBlock: createKeyword({
```
Comment (anneeb) [inline src/sms/tokens.ts:66]: I don't believe this needs to be a keyword

File: src/sms/tokens.ts [hunk 4]
```diff
@@ -107,7 +90,7 @@ export const smsTokenMap = {
     },
     line_breaks: true,
   }),
-  GraphQlBlock: createToken({
+  GraphQlBlock: createKeyword({
```
Comment (anneeb) [inline src/sms/tokens.ts:93]: This one as well is not a keyword

File: src/sms/tokens.ts [hunk 5]
```diff
@@ -33,31 +34,13 @@ const explicitEndMatcher = (
...
-    pattern: /mapping/i,
-  }),
-  SqlBlock: createToken({
+  Template: createKeyword({ name: 'Template' }),
+  Sql: createKeyword({ name: 'Sql' }),
+  GraphQl: createKeyword({ name: 'GraphQl' }),
+  Json: createKeyword({ name: 'Json' }),
+  Csv: createKeyword({ name: 'Csv' }),
+  Mapping: createKeyword({ name: 'Mapping' }),
+  SqlBlock: createKeyword({
```
Comment (anneeb) [inline src/sms/tokens.ts:43]: This block is not a keyword

File: src/sms/tokens.ts (hunk 2 above)
Comment (anneeb) [reply src/sms/tokens.ts:3]: On second thought, it might be better to import this directly from the helpers instead of through the sparql keywords file

File: src/helpers/chevrotain.ts (hunk 1 above)
Comment (anneeb) [reply src/helpers/chevrotain.ts:1]: Oh, I see it in `sparql/keywords` now, just not in `sms/tokens`. It might be better to name it something that isn't so close to the chevrotain module. If you imagine this file also holding other token helpers maybe `tokens`, or otherwise `createKeyword`

File: src/helpers/chevrotain.ts [hunk 6]
```diff
@@ -0,0 +1,12 @@
...
+
+const createKeyword = ({ name, pattern, ...props }: ITokenConfig) =>
+  createToken({
+    name,
+    pattern: pattern || new RegExp(name, 'i'),
+    ...props,
+  });
+
+export default {
```
Comment (anneeb) [inline src/helpers/chevrotain.ts:10]: we generally don't use default exports, so you can export the `createKeyword` function as a named export

File: src/sparql/keywords.ts [hunk 7]
```diff
@@ -1,626 +1,152 @@
-// @ts-ignore: import types for declarations
-import { createToken, TokenType } from 'chevrotain';
-
-const MAX_LENGTH = createToken({
+import { ITokenConfig } from 'chevrotain';
+import helper from 'helpers/chevrotain';
+
+export const createKeyword = ({
+  longer_alt = UNKNOWN,
```
Comment (anneeb) [inline src/sparql/keywords.ts:5]: Why not set the default of the `longer_alt` in the helpers? Would that make it possible to import `createKeyword` directly from the helpers for the SMS tokens rather than from here?

File: src/sparql/keywords.ts [hunk 8]
```diff
@@ -1,626 +1,152 @@
...
+  ...props
+}: ITokenConfig) =>
+  helper.createKeyword({
+    longer_alt,
+    ...props,
+  });
+
+const UNKNOWN = createKeyword({ name: 'UNKNOWN', pattern: /\w+/i });
```
Comment (anneeb) [inline src/sparql/keywords.ts:13]: Unknown isn't technically a keyword, so I don't believe it makes sense to use the create keyword constructor.

File: src/helpers/chevrotain.ts (hunk 1 above)
Comment (cchaffatt) [reply src/helpers/chevrotain.ts:1]: yes, that can work. this file is intended to be a chevrotain helper

File: src/sms/tokens.ts (hunk 2 above)
Comment (cchaffatt) [reply src/sms/tokens.ts:3]: will sms always follow the same `longer_alt` as sparql? 

The helper has a overridable token/keyword and sparql has a token/keyword that defaults `longer_alt` to unknown. This is an intended distinction so any language can create their own flavor of a token/keyword.

This can be useful unless we need all languages to default to unknown

File: src/sms/tokens.ts (hunk 4 above)
Comment (cchaffatt) [reply src/sms/tokens.ts:93]: gotcha, this is a block. I guess we don't care at the moment if we have an augmented block?

`GraphQlBlockoops{}`

That said, not sure what the definition of keyword is.

File: src/sparql/keywords.ts (hunk 7 above)
Comment (cchaffatt) [reply src/sparql/keywords.ts:5]: looks like I explain this on an earlier comment => `src/sms/tokens.ts`

File: src/sms/tokens.ts (hunk 2 above)
Comment (anneeb) [reply src/sms/tokens.ts:3]: I suppose this is SPARQL specific. We want SMS to have the same behavior for keywords as the SPARQL keywords since SMS is extended from SPARQL. In that case it would make sense to keep `createKeyword` defined in the SPARQL keywords.

File: src/sparql/keywords.ts (hunk 8 above)
Comment (cchaffatt) [reply src/sparql/keywords.ts:13]: yes, not really sure what a keyword is. Though it would seem like they are a fall threw class of keywords.

File: src/sms/tokens.ts (hunk 4 above)
Comment (anneeb) [reply src/sms/tokens.ts:93]: A keyword is a collection of non-word characters that is recognized in the grammar of a language to hold some significance. All of our keywords right now have patterns that essentially match a word or multiple words. The block patterns don't actually have the literal string `{blocktype}Block` included in them; they are logic for grabbing all the text within the curly braces that follow the `graphql`, `sql`, `json`, or `csv` keyword.

File: src/sparql/keywords.ts (hunk 8 above)
Comment (anneeb) [reply src/sparql/keywords.ts:13]: Kind of like a programming keyword, it's a word or collection of words that is reserved to have a special meaning or function. Something that is then identified as `unknown` cannot be a keyword since by definition, a keyword is explicitly defined and identified as part of the language.

File: src/helpers/chevrotain.ts (hunk 1 above)
Comment (anneeb) [reply src/helpers/chevrotain.ts]: We do have other files containing methods and types that are essentially "chevrotain helpers" in that provide additional functionality from building around the chevrotain package. For example, `helpers/cst` or `helpers/types` indicates what part of chevrotain we're "helping" or answers the question `what are these helpers for?` Having a file in the helpers called `chevrotainHelper`, especially alongside the existing helper files, is not descriptive as to what kind of functionality this file actually covers. Can you rename this file to be something more specific?

Comment (cchaffatt) [reply src/helpers/chevrotain.ts]: yes, just took a look. Your suggestion for this file was `tokens`. We can use that.

It is also not entirely clear what kind of helpers `helpers/cst`, and `helpers/types` are. These 3 files are better suited in a folder named `chevrotain` .

File: src/sparql/keywords.ts [hunk 9]
```diff
@@ -1,626 +1,152 @@
...
+  MIN: createKeyword({ name: 'MIN' }),
+  AVG: createKeyword({ name: 'AVG' }),
+  SAMPLE: createKeyword({ name: 'SAMPLE' }),
+  GROUP_CONCAT: createKeyword({ name: 'GROUP_CONCAT' }),
+  SEPARATOR: createKeyword({ name: 'SEPARATOR' }),
+  TRUE: createKeyword({ name: 'TRUE' }),
+  FALSE: createKeyword({ name: 'FALSE' }),
+  IN: createKeyword({ name: 'IN' }),
+  NOT_IN: createKeyword({ name: 'NOT_IN', pattern: /NOT IN/i }),
+  MAX: createKeyword({ name: 'MAX', longer_alt: MAX_LENGTH }),
```
Comment (anneeb) [inline src/sparql/keywords.ts:148]: On second thought, I think this should also use the `unknown` longer_alt. We can use the token ordering to match `max_length` first, then use the `unknown` longer_alt for `max` (ie. `maximum`), then `max` itself. This would mean that `MAX_LENGTH`, currently defined at the top of the file, can also be defined in line like the rest of the keywords.

**Comment by jmrog** [comment]
@cchaffatt Can you change the title of this PR before we merge, since it isn't accurate now?
